[package]
name = "tlinalg"
description = "faer-backed implementation of the tlinalg tensor-free numerical interface."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
faer = { workspace = true }
num-complex = { workspace = true }
rayon = { workspace = true }
tlinalg-traits = { workspace = true }

[lints]
workspace = true
